
THORSANVIL_ROOT				= $(realpath ../../)

TARGET						= ThorSerialize.slib

CPPFLAGS					+= -I/Users/myork/Repository/TS.old/build/include/
LDLIBS						+= -L/Users/myork/Repository/TS.old/build/lib/ -lyaml
UNITTEST_RUNTIME_PATH		+= /Users/myork/Repository/TS.old/build/lib/
%/JsonLexer.lex.o:			FILE_WARNING_FLAGS	+= -Wno-deprecated-register

include $(THORSANVIL_ROOT)/build/tools/Makefile




