
THORSANVIL_ROOT				= $(realpath ../)

XTARGET						= ThorsLogging GitUtility ThorsIOUtil Serialize ThorsStorage
TARGET						= ThorsStorage

include $(THORSANVIL_ROOT)/build/tools/Project.Makefile




