
THORSANVIL_ROOT				= $(realpath ../)

TARGET						= ThorsLogging GitUtility ThorsIOUtil Serialize ThorsStorage ThorsCrypto ThorsSocket ThorsMongo

include $(THORSANVIL_ROOT)/build/tools/Project.Makefile




