name: GitHub-CI for ci-test

run-name:   ${{ github.actor }} is learning
on:         [push]

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false          # don't abort other jobs if a job fails
      matrix:
        config:
          - {
              name:     "Ubuntu Linux",
              os:       ubuntu-latest,
              shell:    bash,
              cc:       gcc,
              cxx:      g++,
            }
          - {
              name:     "MacOS",
              os:       macos-latest,
              shell:    bash,
              cc:       gcc,
              cxx:      g++
            }
          - {
              name:     "Windows 64-bit",
              os:       windows-latest,
              shell:    'msys2 {0}',
              cc:       x86_64-w64-mingw32-gcc.exe,
              cxx:      x86_64-w64-mingw32-g++.exe,
              msystem:  MINGW64,
              vera:     --disable-vera
            }
    name:    ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell:  ${{ matrix.config.shell }}
    env:
      CC:   ${{ matrix.config.cc }}
      CXX:  ${{ matrix.config.cxx }}

    steps:
    - if: matrix.config.os == 'ubuntu-latest'
      name: Install build dependencies (Linux)
      run: |
        sudo apt-get install vera++
        sudo apt-get install libboost-all-dev
        sudo apt-get install libyaml-dev
    - if: matrix.config.os == 'macos-latest'
      name: Install build dependencies (macOS)
      run: |
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew install vera++
        brew install boost
        brew install libyaml
    - if: matrix.config.os == 'windows-latest'
      name: Install build dependencies (Windows)
      uses: msys2/setup-msys2@v2
      with:
        update: false
        msystem: ${{ matrix.config.msystem }}
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-yaml-cpp
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-dlfcn
    - uses: actions/checkout@master
    - name: Build
      run: |
        git clone https://github.com/Neargye/magic_enum.git /tmp/magic_enum
        ./configure --enable-dark-mode --with-magicenumroot=/tmp/magic_enum ${{ matrix.config.yaml }} ${{ matrix.config.vera }}
        make
        make install

