name:       Build
run-name:   ${{ github.actor }} is learning
on:         [push]
jobs:
        #  windows-latest
        #  windows-2022
        #  windows-2019
        #  ubuntu-latest
        #  ubuntu-22.04
        #  ubuntu-20.04
        #  ubuntu-18.04
        #  macos-latest
        #  macos-13
        #  macos-12
        #  macos-11
    Build_on_Mac:
        runs-on:    macos-latest
        steps:
            - run: env HOMEBREW_NO_AUTO_UPDATE=1 brew install vera++
            - run: env HOMEBREW_NO_AUTO_UPDATE=1 brew install boost
            - run: env HOMEBREW_NO_AUTO_UPDATE=1 brew install magic_enum
            - uses: actions/checkout@master
            - run: ./configure
            - run: make
            - run: make install
    Build_on_Linux:
        runs-on:    ubuntu-latest
        steps:
            - run: sudo apt-get install vera++
            - run: sudo apt-get install libboost-all-dev
            - run: git clone https://github.com/Neargye/magic_enum.git /tmp/magic_enum
            - uses: actions/checkout@master
            - run: ./configure --enable-dark-mode --with-magicenumroot=/tmp/magic_enum
            - run: make
            - run: sudo make install

